import { fingerprint, nowISO, safeNumber, uid } from './utils.js';
import { transact, normalizeWine, ensureStoredBottles, makeBottle, normalizeLayoutInState, movement, actor, LIMITS, setBottlePositionInState } from './store-core.js';

export async function addWine(info,quantity=1){quantity=Math.max(1,Math.floor(safeNumber(quantity,1)));return transact(s=>{const fp=fingerprint(info);let w=s.wines.find(x=>fingerprint(x)===fp&&fp.replace(/\|/g,'')!=='');if(w){w.quantity+=quantity;ensureStoredBottles(w);if(!w.imageUrl&&info.imageUrl){w.imageUrl=info.imageUrl;w.imagePublicId=info.imagePublicId||'';}w.updatedAt=nowISO();}else{w=normalizeWine({...info,id:uid('wine'),quantity,createdAt:nowISO(),updatedAt:nowISO(),bottles:[]},s.wines.length);ensureStoredBottles(w);s.wines.push(w);}normalizeLayoutInState(s,false);movement(s,{type:'entrada',wineId:w.id,wineName:w.wineName,quantity,detail:'Entrada de garrafa(s)'});return w.id;});}
export async function updateWine(wineId,patch={}){return transact(s=>{const w=s.wines.find(x=>x.id===String(wineId));if(!w)throw new Error('Vinho não encontrado.');const oldName=w.wineName,requestedLocation=Object.prototype.hasOwnProperty.call(patch,'location')?patch.location:null;Object.assign(w,patch,{id:w.id,updatedAt:nowISO()});w.quantity=Math.max(0,Math.floor(safeNumber(w.quantity,0)));ensureStoredBottles(w);if(requestedLocation!==null&&w.quantity>0){const first=w.bottles.find(b=>b.status==='stored');if(first)setBottlePositionInState(s,w,first,requestedLocation);}movement(s,{type:'edicao',wineId:w.id,wineName:w.wineName,quantity:0,detail:oldName===w.wineName?'Cadastro atualizado':`Nome alterado de ${oldName}`});});}
export async function adjustQuantity(wineId,delta,details={}){delta=Math.trunc(safeNumber(delta,0));if(!delta)return;return transact(s=>{const w=s.wines.find(x=>x.id===String(wineId));if(!w)throw new Error('Vinho não encontrado.');ensureStoredBottles(w);if(delta>0){for(let i=0;i<delta;i++)w.bottles.push(makeBottle(w,details));w.quantity+=delta;movement(s,{type:'entrada',wineId:w.id,wineName:w.wineName,quantity:delta,detail:details.detail||'Ajuste positivo de estoque'});}else{const count=Math.min(w.quantity,Math.abs(delta)),stored=w.bottles.filter(b=>b.status==='stored');for(let i=0;i<count;i++){const b=stored[stored.length-1-i];if(b){b.status=details.status||'adjusted_out';b.openedAt=nowISO();b.notes=details.detail||b.notes;}}w.quantity-=count;movement(s,{type:details.type||'saida',wineId:w.id,wineName:w.wineName,quantity:-count,detail:details.detail||'Ajuste negativo de estoque'});}normalizeLayoutInState(s,false);w.updatedAt=nowISO();});}
export async function openBottle(wineId,tasting=null){return transact(s=>{const w=s.wines.find(x=>x.id===String(wineId));if(!w||w.quantity<=0)throw new Error('Não há garrafa disponível deste rótulo.');ensureStoredBottles(w);const b=[...w.bottles].reverse().find(x=>x.status==='stored');if(b){b.status='consumed';b.openedAt=nowISO();}w.quantity--;w.updatedAt=nowISO();movement(s,{type:'consumo',wineId:w.id,wineName:w.wineName,bottleId:b?.id||'',quantity:-1,detail:tasting?.food?`Consumido com ${tasting.food}`:'Garrafa aberta/consumida'});if(tasting){s.v2.tastings.unshift({id:uid('taste'),at:nowISO(),wineId:w.id,wineName:w.wineName,year:w.year||'',rating:Math.max(0,Math.min(5,safeNumber(tasting.rating,0))),food:tasting.food||'',occasion:tasting.occasion||'',companions:tasting.companions||'',notes:tasting.notes||'',actor:actor(s)});s.v2.tastings=s.v2.tastings.slice(0,LIMITS.tastings);}});}
export async function assignBottleLocation(wineId,bottleId,location){return transact(s=>{const w=s.wines.find(x=>x.id===String(wineId));if(!w)throw new Error('Vinho não encontrado.');ensureStoredBottles(w);const b=w.bottles.find(x=>x.id===String(bottleId));if(!b||b.status!=='stored')throw new Error('Garrafa não disponível.');const{previous,target}=setBottlePositionInState(s,w,b,location);movement(s,{type:'localizacao',wineId:w.id,wineName:w.wineName,bottleId:b.id,quantity:0,detail:`${previous?`posição ${previous}`:'sem posição'} → ${target?`posição ${target}`:'sem posição'}`});});}
export async function toggleFavorite(wineId){return transact(s=>{const w=s.wines.find(x=>x.id===String(wineId));if(w){w.favorite=!w.favorite;w.updatedAt=nowISO();}});}
export async function deleteWine(wineId){return transact(s=>{const i=s.wines.findIndex(x=>x.id===String(wineId));if(i<0)return;const w=s.wines[i];movement(s,{type:'exclusao',wineId:w.id,wineName:w.wineName,quantity:-w.quantity,detail:'Rótulo removido da adega'});s.wines.splice(i,1);});}
